# Generated by Django 4.1.4 on 2022-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontosturisticos_recurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontosturisticos',
            old_name='provado',
            new_name='aprovado',
        ),
    ]
