# Generated by Django 4.1.4 on 2022-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_rename_comentarios_comentario'),
        ('core', '0005_alter_pontosturisticos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
