# Generated by Django 4.1.4 on 2023-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_docidentificacao_pontoturistico_doc_identificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docidentificacao',
            name='descricao',
        ),
        migrations.AddField(
            model_name='docidentificacao',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
