# Generated by Django 4.1.4 on 2023-01-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_docidentificacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docidentificacao',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
