# Generated by Django 4.1.4 on 2023-01-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_docidentificacao_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docidentificacao',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
