# Generated by Django 4.1.4 on 2022-12-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enderereco',
            new_name='Endereco',
        ),
    ]
