# Generated by Django 4.1.4 on 2022-12-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracao',
            new_name='Recursos',
        ),
    ]
