# Generated by Django 4.1.4 on 2022-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_rename_atracao_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='horario_func',
            field=models.TextField(verbose_name='Horário de funcionamento'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Recurso disponibilizado'),
        ),
    ]
