# Generated by Django 4.1.4 on 2022-12-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pontosturisticos_descricao'),
        ('atracoes', '0003_alter_recursos_descricao_alter_recursos_horario_func_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recurso',
        ),
    ]
