# Generated by Django 4.1.4 on 2022-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0004_rename_recursos_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recursos', verbose_name='Imagem'),
        ),
    ]
